version: '3'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    container_name: organizer_db
    volumes:
      - ./postgres:/kvar/lib/postgresql/data
